Rewritten to a database Orm + Queue triggers
itk-dev-rpa/OpenOrchestrator pull request #31
Opened 2023-11-01 13:53 UTC by ghbm-itk

The entire project has been refactored to use an ORM (SQLAlchemy) for all database interactions.

Email triggers are gone.
Queue triggers and job queues has been implemented in both Orchestrator and Scheduler.

A bunch of minor fixes and refactors.

2023-11-02 09:45 UTC, rimi-itk requested changes
Some comments and suggestions added. Please note that I'm not a real Python programmer and some comments may completely miss the point.

2023-11-02 09:45 UTC, rimi-itk commented on OpenOrchestrator/database/db_util.py
I have a strong feeling that most stuff in this file is superfluous and are leftovers from the days before using SQLAlchemy. It may be useful for creating and updating the database schema, but all select, update and delete stuff should probably be handled elsewhere.

I don't know how to do it in SQLAlchemy/Python, but rather than calling`db_util.get_scheduled_triggers`, say, it would seem nicer to use a repository (https://dddinpython.com/index.php/2022/11/09/implementing-the-repository-pattern-using-sqlalchemy/) or just using the SQLAlchemy Session (cf. https://gist.github.com/uris77/4711015?permalink_comment_id=2313907#gistcomment-2313907).

Pseudo example:

```py
triggers = trigger_repository.find_all()
…

trigger = trigger_repository.find(id=87)
…
```

However, I don't know if/how this i doable with SQLAlchemy or if it's the way to do it.

2023-11-02 09:45 UTC, rimi-itk commented on OpenOrchestrator/database/db_util.py
> +        return tuple(result)
Why do you convert the result to a tuple? The result is already an iterator.

2023-11-02 09:45 UTC, rimi-itk commented on OpenOrchestrator/orchestrator/constants_tab.py
> +        name, value, _ = const_table.item(row, 'values')
```suggestion
        name, value, *_ = const_table.item(row, 'values')
```

(cf. https://peps.python.org/pep-3132/)

2023-11-02 09:45 UTC, rimi-itk commented on OpenOrchestrator/orchestrator/constants_tab.py
> +        name, value, _, _ = cred_table.item(row, 'values')
```suggestion
        name, value, *_ = const_table.item(row, 'values')
```

(cf. https://peps.python.org/pep-3132/)

2023-11-02 15:02 UTC, ghbm-itk commented on OpenOrchestrator/database/constants.py
> +    """SqlAlchemy base class for all ORM classes in this module."""
As far as I understand the base class may not have mapped variables, so I would need a subclass underneath that as a base for further classes.

2023-11-02 15:07 UTC, ghbm-itk commented on OpenOrchestrator/database/constants.py
> +    def as_tuple(self) -> tuple:
Python is a silly language where everybody do what they want. "to_tuple" is probaly better but try saying it 10 times

2023-11-02 15:09 UTC, ghbm-itk commented on OpenOrchestrator/database/constants.py
> +class Credential(Base):
When talking about constants and credentials they are often grouped together. In a strict programmatic sense no, but in our daily work, yes.

Credential could have been an extension of constant, but I felt it made the code and sql tables more complex than needed.

2023-11-02 15:21 UTC, ghbm-itk commented on OpenOrchestrator/database/db_util.py
> +        return tuple(result)
"Iterator" can mean a lot of things in python. Some iterators are consumed and thus become empty after iteration. I don't know if SQLAlchemy provide a persistent iterator or not, but this way I'm sure what output I get.

2023-11-03 07:18 UTC, ghbm-itk commented on OpenOrchestrator/database/db_util.py
I did consider moving all object specific code into the modules where the ORM classes are defined e.g. get_constants in constants.py. 
At the moment I don't see the value of a rewrite outweighing the work.

2023-11-03 07:22 UTC, ghbm-itk commented on OpenOrchestrator/database/constants.py
> +    change_date: Mapped[datetime] = mapped_column(onupdate=datetime.now, default=datetime.now)
Done

2023-11-07 08:15 UTC, rimi-itk approved these changes

2023-11-07 08:22 UTC, merged