Feature/new buttons + proper process running + OrchestratorConnection added
itk-dev-rpa/OpenOrchestrator pull request #33
Opened 2023-11-10 12:01 UTC by ghbm-itk

Orchestrator:
  Added Enable/Disable buttons to trigger tab.
  Added ability to double click triggers to edit them.

Scheduler:
  Added process_arguments to be passed to robots.
  Added cleanup of cloned git repos.

OrchestratorConnection merged from separate project into this project.

Misc minor fixes

2023-11-10 13:06 UTC, Krogsager submitted a review, later dismissed

2023-11-10 14:12 UTC, rimi-itk requested changes

2023-11-10 14:12 UTC, rimi-itk commented on OpenOrchestrator/scheduler/runner.py
> +    subprocess.run(['rmdir', '/s', '/q', repo_folder], check=False, shell=True)
You should use `os` for stuff like this is possible (cf. https://ioflood.com/blog/python-delete-file-how-to-remove-a-file-or-folder-in-python/)

2023-11-10 14:12 UTC, rimi-itk commented on OpenOrchestrator/scheduler/runner.py
> +    desktop_path = os.path.expanduser("~\\Desktop")
Use `os.path.join` to build the path:

```suggestion
    desktop_path = os.path.expanduser(os.path.join(`~`, 'Desktop'))
```

2023-11-10 14:12 UTC, rimi-itk commented on OpenOrchestrator/scheduler/runner.py
> +    repo_path = os.path.join(desktop_path, "Scheduler_Repos")
Where is the documentation telling that repositories must be cloned into `~/Desktop/Scheduler_Repos`?

2023-11-10 14:12 UTC, rimi-itk commented on README.md
Consider using https://pypi.org/project/pymarkdownlnt/ to lint your Markdown files.

2023-11-14 07:07 UTC, ghbm-itk commented on OpenOrchestrator/scheduler/runner.py
> +    subprocess.run(['rmdir', '/s', '/q', repo_folder], check=False, shell=True)
os or shutil cannot remove git repos... Git still has control of the folder according to python. This was the only solution I could find that worked

2023-11-14 07:14 UTC, ghbm-itk commented on OpenOrchestrator/scheduler/runner.py
> +    repo_path = os.path.join(desktop_path, "Scheduler_Repos")
All that happens automatically. No user action needed

2023-11-14 07:20 UTC, ghbm-itk commented
Further testing has showed that using .bat files to run robots can result in some obscure bugs. For now .bat support is being removed.

2023-11-14 08:37 UTC, rimi-itk commented on OpenOrchestrator/scheduler/runner.py
> +    subprocess.run(['rmdir', '/s', '/q', repo_folder], check=False, shell=True)
Hmm … It's just a folder that happens to contain a `.git` folder.

2023-11-14 08:37 UTC, rimi-itk approved these changes

2023-11-14 08:57 UTC, ghbm-itk commented on OpenOrchestrator/scheduler/runner.py
> +    subprocess.run(['rmdir', '/s', '/q', repo_folder], check=False, shell=True)
shutil.rmtree would be the correct qay to go, but it will leave 1-2 files in the .git folder because "the files are in use by another program". rmdir would give the same error if the files where actually in use, but it doesn't

2023-11-14 08:58 UTC, merged

2023-11-14 09:02 UTC, rimi-itk commented on OpenOrchestrator/scheduler/runner.py
> +    subprocess.run(['rmdir', '/s', '/q', repo_folder], check=False, shell=True)
That's weird. Do you have a git client, like https://desktop.github.com/, say, running that keeps track of git folder (and uses the files)?