Added LimitedLengthString type to avoid log errors
itk-dev-rpa/OpenOrchestrator pull request #87
Opened 2024-06-05 12:59 UTC by bakspace-itk

2024-06-11 06:41 UTC, ghbm-itk requested changes
I would like some tests of this added to the automated tests

2024-06-13 13:55 UTC, bakspace-itk commented
Pull request was closed when issue was removed from release.

2024-06-14 06:38 UTC, ghbm-itk commented on changelog.md
> +- Added truncated string method for limiting long logs
I think this should be under 'Changed'.
And it should be more specific: "Log messages over 8000 characters are now truncated preserving the beginning and end"

2024-06-18 06:21 UTC, ghbm-itk requested changes

2024-06-18 06:21 UTC, ghbm-itk commented on changelog.md
> +- Log messages over 8000 characters are now truncated preserving the beginning and end
```suggestion
- Log messages over 8000 characters are now truncated preserving the beginning and end.
```

2024-06-18 08:09 UTC, ghbm-itk approved these changes

2024-06-18 08:36 UTC, ghbm-itk approved these changes

2024-06-18 10:18 UTC, merged