Everything!
itk-dev-rpa/OpenOrchestrator pull request #9
Opened 2023-09-19 11:47 UTC by ghbm-itk

2023-09-20 08:35 UTC, rimi-itk commented on .pylintrc
> +ignore-paths = ^tests/ # Ignore the tests folder
Why is `tests/` ignored? Tests also contain code that must adhere to the coding standards.

2023-09-21 08:14 UTC, ghbm-itk commented on .github/workflows/pylint.yml
> +on: [push]
Why is this better?

2023-09-21 12:28 UTC, ghbm-itk commented on .pylintrc
> +  C0103, # Variable names
We disabled it because at the time it only detected "variable name shorter than 3 letters" and that seemed pointless. I didn't notice the long list of other checks, because I already followed them. It will be re-enabled

2023-09-21 12:29 UTC, ghbm-itk commented on .pylintrc
> +  W0621, # Redefine outer name
This was copied from another project where it made sense. I will re-enable it

2023-09-21 12:50 UTC, rimi-itk commented on .github/workflows/pylint.yml
> +on: [push]
I really don't know what the difference between `push` and `pull_request` is, but https://stackoverflow.com/a/73297089 tries to explain it.

In all other ITK Dev-projects we use `on: pull_request` in an `pr.yaml` file (cf. https://github.com/itk-dev/os2forms_selvbetjening/blob/develop/.github/workflows/pr.yaml). All code changes should come from pull requests and therefore it makes sense to use `on: pull_request` (the action is run whenever the pull request is updated (via `git push`)).

2023-09-28 09:04 UTC, ghbm-itk commented on OpenOrchestrator/Orchestrator/Table_util.py
> +        string += f'echo "{str(table.item(item, "values"))}" & '
table.selection() returns a list of ids (string). I will rename 'item'.

2023-10-05 06:22 UTC, ghbm-itk commented on OpenOrchestrator/Common/db_util.py
An issue has been created for the future

2023-10-05 06:22 UTC, ghbm-itk commented on OpenOrchestrator/Orchestrator/SQL/Initialize_Database.sql
An issue has been created for the future

2023-10-05 08:25 UTC, rimi-itk requested changes

2023-10-05 08:25 UTC, rimi-itk commented on .github/workflows/pylint.yml
> +        pylint --rcfile=.pylintrc $(git ls-files '*.py') --good-names=OpenOrchestrator
All options and arguments to `pylint` (apart from `--rcfile`) should be put in `.pylintrc` to make sure that the same checks are performed by the Action and locally during development.

Even `--rcfile=.pylintrc` can be omitted when using `.pylintrc` (the default configuration file name) as the configuration file name (cf. https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#command-line-options).

`README.md` should tell how to install this project and how to set it up for development – and how to run code analysis (locally).

2023-10-05 09:20 UTC, rimi-itk approved these changes

2023-10-05 09:25 UTC, merged